# Generated by Django 4.2.21 on 2025-05-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название предмета')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('description', models.CharField(max_length=10000, verbose_name='Описание предмета')),
            ],
        ),
    ]
