# Generated by Django 4.2.21 on 2025-05-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StripeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank='', max_length=10000, verbose_name='Описание предмета'),
        ),
        migrations.AlterModelTable(
            name='item',
            table='Item',
        ),
    ]
