# Generated by Django 4.2.21 on 2025-05-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StripeApp', '0002_alter_item_options_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Описание предмета'),
        ),
    ]
