# Generated by Django 4.2.21 on 2025-06-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StripeApp', '0003_alter_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(related_name='order_items', to='StripeApp.item', verbose_name='Предметы в заказе')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'Order',
            },
        ),
    ]
