# Generated by Django 4.2.21 on 2025-06-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StripeApp', '0006_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(related_name='order_items', to='StripeApp.orderitem', verbose_name='Предметы в заказе'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
